excerpt_separator: ""
markdown: kramdown
url: http://collectiveleap.github.io
title: Collective Leap
tagline: experiments in making tools for making sense
description: experiments in making tools for making sense
paginate: 5
